spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/shopping_test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 10000

  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.host:6379}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true # 로컬에서만 aws 로그 남기면 비용 부담
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          timezone: Asia/Seoul

jwt:
  secret: ${kt.jwt.secret:kt-cloud-tech-up-shopping-251117}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000}
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000}

slack:
  bot-token: ${slack.token}
  logChannel: ${slack.channel}